"""add phone number

Revision ID: 32583e43ed97
Revises: 503371726bb9
Create Date: 2023-07-15 22:04:49.009958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32583e43ed97'
down_revision = '503371726bb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
