"""add-vote

Revision ID: 503371726bb9
Revises: c38eb2d096dc
Create Date: 2023-07-15 21:54:53.767492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503371726bb9'
down_revision = 'c38eb2d096dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
